@endpoint = https://jpyq00mwve.execute-api.ap-northeast-1.amazonaws.com/prod/

GET {{endpoint}}/hello/

###

GET {{endpoint}}/spaces?spaceId=85a38cbd-4ffd-41c5-af4e-0ae797ed80bb
###
PUT {{endpoint}}/spaces?spaceId=85a38cbd-4ffd-41c5-af4e-0ae797ed80bb
Content-Type: application/json

{
  "location": "Updated London",
}
###

GET {{endpoint}}/spaces?location=London

###

###
POST {{endpoint}}/spaces/
Content-Type: application/json

{
  "location": "London",
  "name": "Best location"
}